### ISSUE TITLE
heroku ApplicationError

### ISSUE THREAD

**Issue by liangxinhui** [songchenwen/hexo-migrator-issue#1]
```
2015-03-07T13:35:53.263859+00:00 heroku[api]: Release v2 created by liangxinhui@gmail.com
2015-03-07T13:35:53.263859+00:00 heroku[api]: Enable Logplex by liangxinhui@gmail.com
2015-03-07T13:40:27.457209+00:00 heroku[api]: Scale to web=1 by liangxinhui@gmail.com
2015-03-07T13:40:27.615003+00:00 heroku[api]: Deploy d6edac6 by liangxinhui@gmail.com
2015-03-07T13:40:27.615003+00:00 heroku[api]: Release v3 created by liangxinhui@gmail.com
2015-03-07T13:40:40.739763+00:00 heroku[web.1]: Starting process with command `npm install; node app.js;`
2015-03-07T13:40:42.201297+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-03-07T13:40:42.201318+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-03-07T13:40:44.904610+00:00 app[web.1]: ^
2015-03-07T13:40:44.904612+00:00 app[web.1]: TypeError: undefined is not a function
2015-03-07T13:40:44.904603+00:00 app[web.1]: /app/app.js:164
2015-03-07T13:40:44.904608+00:00 app[web.1]: hexo_init({command: 'version'}, function(){
2015-03-07T13:40:44.904613+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:164:1)
2015-03-07T13:40:44.904641+00:00 app[web.1]:     at startup (node.js:129:16)
2015-03-07T13:40:44.904615+00:00 app[web.1]:     at Module._compile (module.js:460:26)
2015-03-07T13:40:44.904639+00:00 app[web.1]:     at Function.Module.runMain (module.js:501:10)
2015-03-07T13:40:44.904635+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:478:10)
2015-03-07T13:40:44.904638+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-03-07T13:40:44.904637+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-03-07T13:40:44.904643+00:00 app[web.1]:     at node.js:814:3
2015-03-07T13:40:45.582610+00:00 heroku[web.1]: Process exited with status 1
2015-03-07T13:40:48.591869+00:00 heroku[web.1]: Starting process with command `npm install; node app.js;`
2015-03-07T13:40:45.601353+00:00 heroku[web.1]: State changed from starting to crashed
2015-03-07T13:40:45.601353+00:00 heroku[web.1]: State changed from crashed to starting
2015-03-07T13:40:50.460300+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-03-07T13:40:50.460325+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-03-07T13:40:54.752884+00:00 heroku[api]: Scale to web=1 by liangxinhui@gmail.com
```

**Comment by liangxinhui** [comment]
调查了一下，原因是3.0版本更新时，Hexo的API有调整。
例如，初始化时改为：

``` javascript
var Hexo = require('hexo');
var hexo = new Hexo(process.cwd(), {});

hexo.init().then(function(){
  // ...
});
```

参考：
http://hexo.io/zh-cn/api/index.html
https://github.com/hexojs/hexo/wiki/Breaking-Changes-in-Hexo-3.0

**Comment by liangxinhui** [comment]
我刚接触Node.js，初始化的问题改好了，后续又发现git发布的时候过不去。
修改起来比较费劲

希望抽空将插件升级到3.0版本
